### ISSUE TITLE
Variables starting with "switch" incorrectly highlighted

### ISSUE THREAD

**Issue by kilbouri** [dotnet/csharp-tmLanguage#221]
## Details

**What editor are you seeing the problem in? (e.g. Atom, Visual Studio Code, etc.)**

VS Code.
In fact, while writing this report, it seems to be independent of VS Code entirely (see code sample under Reproduction).

**What version of the editor are you using?**

Version: 1.60.1 (user setup)
Commit: 83bd43bc519d15e50c4272c6cf5c1479df196a4d
Date: 2021-09-10T17:07:10.714Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042

**What color theme are you using?**
Default dark (appears in others as well)

## Reproduction
Try this code:
```cs
int switchVariable = 1;
if (switchVariable != 0) {
    return;
}
```

You should see this:
![image](https://user-images.githubusercontent.com/52428953/133512961-f58727b9-c752-42b5-87d7-1ff2daa4c363.png)
Semantic Highlighting option appears to have no effect (yes, I did re-open the file afterwards)
EDIT: I forgot to switch to a ligature-less font when taking the screenshot. Note that the shown `=/=` is just a fancy ligature for `!=` and as such you may not see that.

**Comment by JoeRobich** [comment]
Closing as this issue was resolved with https://github.com/dotnet/csharp-tmLanguage/pull/219. It should automatically get brought into VS Code in a future version. In the meantime you can set `csharp.semanticHighlighting.enabled` to `true` in your settings to enabled the more accurate semantic highlighting.

**Comment by kilbouri** [comment]
> Closing as this issue was resolved with #219. It should automatically get brought into VS Code in a future version. In the meantime you can set `csharp.semanticHighlighting.enabled` to `true` in your settings to enabled the more accurate semantic highlighting.

As mentioned in the report, semantic highlighting does not resolve the issue. Good to know it has been resolved and I'm just waiting on VSC to pull it. Thanks :)

**Comment by JoeRobich** [comment]
> As mentioned in the report, semantic highlighting does not resolve the issue.

@kilbouri Can you confirm that both `editor.semanticHighlighting.enabled` and `csharp.semanticHighlighting.enabled` were both set to `true` and it didn't resolve this issue? If that is the case, could you open an issue against [OmniSharp-VSCode](https://github.com/OmniSharp/omnisharp-vscode/issues) and provide the requested logs?

**Comment by kilbouri** [comment]
Ah that resolves it. Did not know there were two places to enable it. Sorry for the confusion!
